#:schema https://raw.githubusercontent.com/lapce/lapce/master/extra/schemas/color-theme.json
[color-theme]
name = "Ros√© Pine Moon"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[color-theme.base]
white = "#e0def4"
black = "#6e6a86"
grey = "#393552"
blue = "#9ccfd8"
red = "#eb6f92"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#3e8fb0"
purple = "#c4a7e7"
cyan = "#ea9a97"
magenta = "#c4a7e7"

[color-theme.syntax]
"comment" = "#6e6a86"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "#ea9a97"
"method" = "$green"
"function.method" = "#9ccfd8"
"keyword" = "$green"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "$yellow"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"
# "label" = "#c4a7e7"
"variable" = "#e0def4"
# "operator" = "#ea9a97"
# "symbol" = ""
# "punctuation" = ""
# "punctuation.special" = ""
# "punctuation.delimiter" = ""
# "text" = "#e0def4"
# "text.literal" = ""
# "text.title" = ""
# "text.uri" = ""
# "text.reference" = ""
# "string.escape" = ""
# "conceal" = ""
# "none" = ""
"tag" = "$blue"

[color-theme.ui]

"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#000000"
"lapce.scroll_bar" = "$grey"

"lapce.button.primary.background" = "#ea9a97"
"lapce.button.primary.foreground" = "#232136"


# tab
"lapce.tab.active.background" = "#817c9c14"
"lapce.tab.active.foreground" = "#e0def4"
"lapce.tab.active.underline" = "#528BFF"

"lapce.tab.inactive.background" = "#0000"
"lapce.tab.inactive.foreground" = "#908caa"
"lapce.tab.inactive.underline" = "#528BFF77"

"lapce.tab.separator" = ""

"editor.background" = "#232136"
"editor.foreground" = "$white"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#528BFF"
"editor.selection" = "$grey"
"editor.current_line" = "#39355288"
"editor.link" = "$cyan"

"inlay_hint.foreground" = "$white"
"inlay_hint.background" = "#56526e88"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E06C7520"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.other.foreground" = "#5C6370"
"error_lens.other.background" = "#5C637020"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "#2a273f"
"palette.foreground" = "#e0def4"
"palette.current.background" = "#39355280"
"palette.current.foreground" = "$white"

"completion.background" = "#232136"
"completion.current" = "#39355280"

"hover.background" = "#232136"

"activity.background" = "#232136"
"activity.current" = "#ea9a97"

"panel.background" = "#2a273f"
"panel.foreground" = "#e0def4"
"panel.foreground.dim" = "#5C6370"
"panel.current.background" = "#39355280"
"panel.current.foreground" = "#232136"
"panel.current.foreground.dim" = "#5C6370"
"panel.hovered.background" = "#39355280"
"panel.hovered.foreground" = "#232136"
"panel.hovered.foreground.dim" = "#5C6370"

"status.background" = "#232136"
"status.foreground" = "#908caa"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#2a283e"

"terminal.cursor" = "#56526e"
"terminal.foreground" = "$white"
"terminal.background" = "#232136"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$white"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$black"
